In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available:
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Using GPU: Tesla T4


# Create a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.2285, 0.6498, 0.9753],
        [0.7468, 0.6054, 0.3503]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[140322670509440, 140322670509440,               0],
        [     1065353216,               0,               0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [21]:
# find data type
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operation

## 1. Scalar Operation

In [26]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [30]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

## 2. Element Wise Operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a,b)

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]]) tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])


In [34]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1394, 0.4235, 0.0169],
        [0.0056, 0.3059, 0.0204]])

In [3]:
c = torch.tensor([1, -2, 3, -4])

In [4]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [5]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [6]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [7]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [8]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [10]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [11]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction **Operation**

In [12]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 2., 2.],
        [8., 0., 7.]])

In [13]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([12., 15.])

In [14]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([8.0000, 1.0000, 4.5000])

In [15]:
# median
torch.median(e)

tensor(2.)

In [16]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [17]:
# product
torch.prod(e)

tensor(0.)

In [18]:
# standard deviation
torch.std(e)

tensor(3.5637)

In [19]:
# variance
torch.var(e)

tensor(12.7000)

In [20]:
# argmax
torch.argmax(e)

tensor(0)

In [21]:
# argmin
torch.argmin(e)

tensor(4)

## 4. Matrix Operations


In [22]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 2, 1],
        [3, 8, 0]])
tensor([[4, 1],
        [7, 4],
        [1, 1]])


In [23]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[27, 12],
        [68, 35]])

In [24]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [25]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 3],
        [2, 8],
        [1, 0]])

In [26]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 2., 5.],
        [9., 4., 3.],
        [0., 1., 1.]])

In [27]:
# determinant
torch.det(h)

tensor(27.0000)

In [28]:
# inverse
torch.inverse(h)

tensor([[ 0.0370,  0.1111, -0.5185],
        [-0.3333,  0.0000,  1.6667],
        [ 0.3333,  0.0000, -0.6667]])

## 5. Comparison Operations

In [29]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 4, 3],
        [9, 3, 5]])
tensor([[0, 1, 6],
        [1, 5, 9]])


In [30]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## 6. Special Functons

In [31]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 8., 7.],
        [2., 0., 0.]])

In [32]:
# log
torch.log(k)

tensor([[2.1972, 2.0794, 1.9459],
        [0.6931,   -inf,   -inf]])

In [33]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 2.9810e+03, 1.0966e+03],
        [7.3891e+00, 1.0000e+00, 1.0000e+00]])

In [34]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.8284, 2.6458],
        [1.4142, 0.0000, 0.0000]])

In [35]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9997, 0.9991],
        [0.8808, 0.5000, 0.5000]])

In [36]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9909e-01, 9.9966e-01, 9.9909e-01],
        [9.1105e-04, 3.3535e-04, 9.1105e-04]])

In [37]:
# relu
torch.relu(k)

tensor([[9., 8., 7.],
        [2., 0., 0.]])

# Inplace Operations

In [38]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4579, 0.4522, 0.5534],
        [0.7561, 0.8949, 0.2242]])
tensor([[0.8291, 0.2605, 0.5982],
        [0.1212, 0.0416, 0.4120]])


In [39]:
m.add_(n)

tensor([[1.2870, 0.7127, 1.1516],
        [0.8773, 0.9366, 0.6362]])

In [40]:
m

tensor([[1.2870, 0.7127, 1.1516],
        [0.8773, 0.9366, 0.6362]])

In [41]:
torch.relu(m)

tensor([[1.2870, 0.7127, 1.1516],
        [0.8773, 0.9366, 0.6362]])

In [42]:
m.relu_()

tensor([[1.2870, 0.7127, 1.1516],
        [0.8773, 0.9366, 0.6362]])

In [43]:
m

tensor([[1.2870, 0.7127, 1.1516],
        [0.8773, 0.9366, 0.6362]])

# Copying a Tensor

In [44]:
a = torch.rand(2,3)
a

tensor([[0.0877, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [45]:
b = a

In [46]:
b

tensor([[0.0877, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [47]:
a[0][0] = 0

In [48]:
a

tensor([[0.0000, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [49]:
b

tensor([[0.0000, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [50]:
id(a)

138278822883024

In [51]:
id(b)

138278822883024

In [52]:
b = a.clone()

In [53]:
a

tensor([[0.0000, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [54]:
b

tensor([[0.0000, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [55]:
a[0][0] = 10

In [56]:
a

tensor([[10.0000,  0.5717,  0.2465],
        [ 0.7761,  0.9385,  0.9340]])

In [57]:
b

tensor([[0.0000, 0.5717, 0.2465],
        [0.7761, 0.9385, 0.9340]])

In [58]:
id(a)

138278822883024

In [59]:
id(b)

138278602743664